### ISSUE TITLE
Rtsne.multicore gives different results from Rtsne in higher dimensions

### ISSUE THREAD

**Issue by mattmotoki** [RGLab/Rtsne.multicore#3]
Hi,
I've found Rtsne.multicore to be very useful in 2-dimensions; it produces embeddings that are very similar to those produced by the original Rtsne package.  However, things seem to break down when moving to higher dimensions (in particular 3).  The groupings produced by Rtsne.multicore aren't as coherent as those produced by Rtsne. 

```
library(Rtsne)
library(Rtsne.multicore)

iris_unique <- unique(iris)
mat <- as.matrix(iris_unique[,1:4])

# run calculation 
set.seed(42)
tsne_out <- Rtsne(mat, dims=3)

set.seed(42)
tsne_out_multi <- Rtsne.multicore(mat, dims=3)

# plot results
pairs(tsne_out$Y, col=iris_unique$Species, main="Rtsne")
pairs(tsne_out_multi$Y, col=iris_unique$Species, main="Rtsne.multicore")
```
![rtsne](https://user-images.githubusercontent.com/13989564/27210178-6e43d6b4-5205-11e7-80a6-fdba7c0cb6d4.png)
![rtsne multicore](https://user-images.githubusercontent.com/13989564/27210179-6e44fe54-5205-11e7-830a-9554a2e110e3.png)

**Comment by gfinak** [comment]
This package provides R bindings to Dmitry Ulyanov's multicore tsne. That implementation does not support embedding in D>2. See the issue here:
https://github.com/DmitryUlyanov/Multicore-TSNE/issues/5

**Comment by mattmotoki** [comment]
I see thanks for the quick response.

**Comment by malisas** [comment]
Just want to add that when `dims = 1`, `Rtsne.multicore` also doesn't work. Rstudio actually crashes with the message:
> R session Aborted
> R encountered a fatal error
> The session was terminated

Not sure why. But anyway, I guess I'll just use `Rtsne.multicore` when `dims = 2`!

**Comment by mikejiang** [comment]
The `c++` implementation is tied to `2D` in its [quadTree data structure](https://github.com/DmitryUlyanov/Multicore-TSNE/blob/master/multicore_tsne/quadtree.h#L33), so when you pass `dims = 1`,  it [allocates the memory for `1d` array](https://github.com/DmitryUlyanov/Multicore-TSNE/blob/master/multicore_tsne/tsne.cpp#L179), but still [access(writes) it as `2d` array](https://github.com/DmitryUlyanov/Multicore-TSNE/blob/master/multicore_tsne/quadtree.cpp#L364-L365), which leads to `memory corruption`.
I will restrict `dims` to `2` at R level to avoid the confusion.
